# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

# Hygiene
[[repos]]
repo = "builtin"
hooks = [
    { id = "check-yaml" },
    { id = "check-merge-conflict" },
    { id = "end-of-file-fixer" },
    { id = "trailing-whitespace" },
]

# Secrets
[[repos]]
repo = "https://github.com/Yelp/detect-secrets"
rev = "v1.5.0"
hooks = [
    { id = "detect-secrets", args = ["--baseline", ".secrets.baseline"] },
]

# Go
[[repos]]
repo = "https://github.com/dnephin/pre-commit-golang"
rev = "v0.5.1"
hooks = [
    { id = "go-fmt" },
    { id = "go-vet" },
    { id = "go-build" },
    { id = "go-imports" },
    { id = "go-mod-tidy" },
]

[[repos]]
repo = "https://github.com/golangci/golangci-lint"
rev = "v2.1.6"
hooks = [
    { id = "golangci-lint" },
]

# Commit message
[[repos]]
repo = "local"
hooks = [
    { id = "gitlint", name = "gitlint", description = "Lint commit message (conventional commits)", entry = "gitlint --staged --msg-filename", language = "system", stages = ["commit-msg"] },
]
