smartphone:
  skip_brands:
    - AGM
    - Caterpillar
    - Crosscall
    - Doro
    - Emporia
    - Olympia
    - Sonim
    - SPC
    - Ubiquiti
  exclusion_regex: (?i)\d+W GAN|Adapter|AirTag|Armband|Back Cover|Book Cover|Cable|Case|Charger|Cover\b|Duftkerze|Earphones|Etui|Gimbal|Halterung|Headset|Hülle|Ideal of Sweden|Induktive|Kalender|Kopfhörer|Ladegerät|Ladestation|Lautsprecher|MagSafe|Powerbank|Screen Protector|Schutzfolie|Schutzglas|SmartTag|Stylus|Tastatur|Tisch|Wireless Charger

laptop:
  skip_brands: []
  exclusion_regex: "(?i)Tasche|Sleeve"
